#!/usr/bin/env bash
set -euo pipefail

APP_DATA_DIR="${APP_DATA_DIR:-$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")}"
DATA_DIR="${APP_DATA_DIR}/data"

mkdir -p "${DATA_DIR}"
chmod -R a+rwX "${DATA_DIR}"
